create table client_zoo (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	location VARCHAR(50),
	cat VARCHAR(50),
	dog VARCHAR(50),
	other VARCHAR(50),
	frequency VARCHAR(7),
	sum_order DECIMAL(6,2)
);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (1, 'Betteann', 'Semaine', 'Czech Republic', false, true, true, 'week', 2924.02);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (2, 'Marjorie', 'Seamon', null, false, true, false, 'week', 3548.38);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (3, 'Filbert', 'Napoli', 'Poland', true, false, false, 'month', 3114.94);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (4, 'Helenka', 'Yaakov', 'Poland', true, false, false, 'week', 1412.04);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (5, 'Neel', 'Joselevitz', 'Czech Republic', false, false, true, 'quarter', 5326.35);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (6, 'Pammie', 'Digweed', 'Poland', null, null, null, 'month', 3728.32);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (7, 'Celinka', 'Leere', 'Poland', true, true, false, 'week', 200.02);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (8, 'Westbrooke', 'Anderton', null, false, true, false, 'week', 4029.82);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (9, 'Zarah', 'Dedney', null, true, true, false, 'week', 1904.39);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (10, 'Doug', 'Thowes', 'Poland', null, null, null, 'quarter', 3793.35);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (11, 'Barry', 'Helis', 'Poland', true, true, false, 'week', 5331.16);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (12, 'Linnea', 'Thaw', 'Poland', false, true, false, 'month', 864.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (13, 'Cal', 'Kuhnert', null, false, false, false, 'week', 1556.78);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (14, 'Basilio', 'Fouracres', 'Czech Republic', true, false, false, 'year', 5026.28);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (15, 'Tammara', 'Purvis', 'Poland', false, false, false, 'year', 2310.88);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (16, 'Godiva', 'Dillow', 'Poland', false, false, true, 'month', 397.06);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (17, 'Elka', 'Pierro', 'Poland', false, false, false, 'month', 218.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (18, 'Elvera', 'Piegrome', null, true, false, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (19, 'Leonidas', 'Hiddersley', 'Czech Republic', true, false, true, 'week', 3457.51);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (20, 'Mortie', 'Wythe', 'Germany', false, true, false, 'quarter', 5071.39);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (21, 'Ingrim', 'Felkin', 'Poland', true, false, false, 'quarter', 527.02);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (22, 'Carole', 'Poleye', 'Germany', false, true, false, 'quarter', 1541.19);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (23, 'Coretta', 'Screase', 'Czech Republic', null, null, null, 'week', 1524.16);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (24, 'Raynell', 'Cassell', 'Poland', false, true, false, 'month', 1352.38);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (25, 'Lanae', 'Gowthorpe', 'Poland', true, false, true, 'month', 4558.73);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (26, 'Rory', 'Dearth', null, true, true, true, 'month', 4726.66);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (27, 'Letizia', 'Ridwood', null, false, true, false, 'month', 3402.56);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (28, 'Ced', 'Settle', 'Poland', true, true, true, 'year', 1293.4);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (29, 'Claybourne', 'Tolmie', 'Poland', true, true, false, 'week', 4551.91);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (30, 'Alexei', 'Westnage', 'Poland', false, true, false, 'year', 660.71);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (31, 'Cindra', 'Bedburrow', 'Poland', false, true, true, 'month', 2506.72);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (32, 'Reta', 'Brelsford', 'Poland', false, true, false, 'month', 3564.34);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (33, 'Jethro', 'Papen', null, false, false, false, 'quarter', 3240.3);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (34, 'Birk', 'Troni', null, false, false, true, 'month', 3577.11);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (35, 'Benedetta', 'Embling', 'Poland', false, false, true, 'week', 5800.11);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (36, 'Petey', 'Fussey', null, false, false, false, 'week', 5446.17);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (37, 'Parker', 'Kydde', 'Poland', true, true, false, 'year', 2573.54);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (38, 'Teddy', 'Glashby', 'Poland', false, false, false, 'year', 1216.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (39, 'Flor', 'Collete', 'Poland', false, true, false, 'quarter', 4338.63);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (40, 'Andriette', 'Gegg', null, true, false, true, 'month', 3325.91);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (41, 'Verene', 'McTurley', 'Poland', false, false, false, 'quarter', 1320.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (42, 'Louella', 'Stobo', 'Poland', false, true, true, 'week', 760.27);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (43, 'Iolanthe', 'Lambdean', null, true, true, true, 'week', 852.02);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (44, 'Shani', 'Andreas', 'Poland', false, true, false, 'week', 4506.07);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (45, 'Lora', 'Lucien', 'Poland', true, false, true, 'quarter', 2617.31);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (46, 'Dyanne', 'Speight', null, false, false, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (47, 'Jayne', 'Rabson', 'Poland', false, false, false, 'quarter', 757.82);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (48, 'Wait', 'Fearnyhough', 'Poland', true, true, false, 'quarter', 1215.67);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (49, 'Celka', 'Stanner', 'Czech Republic', false, false, false, 'quarter', 5947.87);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (50, 'Ford', 'Spittles', 'Germany', false, false, false, 'week', 5079.86);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (51, 'Davy', 'Giacobbo', null, true, false, true, 'year', 823.7);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (52, 'Ode', 'Artrick', 'Poland', false, true, true, 'week', 1108.75);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (53, 'Velma', 'Wardingly', null, true, false, true, 'quarter', 5186.57);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (54, 'Deane', 'Huxham', 'Poland', true, true, false, 'week', 1376.77);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (55, 'Anatole', 'Dumbelton', null, true, false, false, 'quarter', 4817.19);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (56, 'Myriam', 'Dosdell', 'Czech Republic', false, true, true, 'month', 2906.42);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (57, 'Arnoldo', 'Yeaman', 'Poland', true, true, false, 'month', 4499.18);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (58, 'Paten', 'Lovejoy', 'Poland', false, false, true, 'month', 5712.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (59, 'Ivonne', 'Ibbotson', null, false, true, false, 'month', 4468.72);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (60, 'Catherina', 'Razzell', 'Poland', null, null, null, 'quarter', 2203.38);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (61, 'Florinda', 'Vint', 'Poland', false, false, true, 'month', 5862.02);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (62, 'Dar', 'Sueter', 'Poland', false, true, true, 'year', 22.37);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (63, 'Tristan', 'Newlands', 'Poland', false, true, false, 'quarter', 5407.23);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (64, 'Pierce', 'Panchin', null, false, false, true, 'year', 968.47);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (65, 'Dael', 'Cordes', null, true, true, false, 'year', 5549.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (66, 'Elysee', 'Cronk', 'Poland', false, true, false, 'quarter', 519.53);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (67, 'Kathy', 'Murden', 'Czech Republic', true, false, false, 'week', 5299.11);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (68, 'Lian', 'Carlyle', 'Poland', false, false, true, 'year', 4250.46);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (69, 'Marcia', 'Brugden', 'Czech Republic', true, true, true, 'month', 3746.04);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (70, 'Garrek', 'McGaugan', 'Poland', false, false, true, 'month', 1063.59);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (71, 'Roddy', 'Tomsett', 'Czech Republic', true, false, false, 'year', 2108.69);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (72, 'Chelsae', 'Wenzel', 'Poland', true, true, false, 'year', 2662.7);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (73, 'Man', 'Smail', 'Poland', true, true, true, 'quarter', 3072.45);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (74, 'Corabelle', 'Arr', 'Czech Republic', true, true, false, 'week', 4630.63);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (75, 'Riannon', 'McDunlevy', 'Germany', false, false, true, 'quarter', 5570.5);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (76, 'Iris', 'Filon', null, true, false, false, 'month', 3691.64);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (77, 'Hakim', 'Komorowski', 'Poland', true, false, false, 'year', 5537.44);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (78, 'Edee', 'Timbridge', null, false, true, false, 'year', 4687.02);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (79, 'Matias', 'Heffron', null, true, false, false, 'month', 5460.53);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (80, 'Lorrie', 'Shmyr', null, true, true, false, 'month', 5385.5);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (81, 'Hamid', 'Rase', 'Czech Republic', false, false, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (82, 'Federica', 'Iacomi', 'Poland', false, true, false, 'quarter', 3596.45);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (83, 'Maudie', 'Roma', 'Czech Republic', false, false, false, 'year', 4827.39);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (84, 'Ulrikaumeko', 'Burchell', 'Poland', false, true, false, 'month', 408.29);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (85, 'Magnum', 'Arlet', 'Czech Republic', false, true, false, 'year', 5811.31);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (86, 'Pierette', 'Tenpenny', 'Poland', true, true, true, 'quarter', 3257.14);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (87, 'Boy', 'Chopin', null, false, true, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (88, 'Percival', 'Date', null, false, false, false, 'year', 5837.61);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (89, 'Merlina', 'Wile', 'Poland', null, null, null, 'year', 1410.72);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (90, 'Zelda', 'Woolfitt', 'Poland', true, false, false, 'month', 32.83);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (91, 'Cora', 'Wiffen', 'Poland', true, false, false, 'week', 3048.19);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (92, 'Reg', 'Florey', null, true, false, true, 'quarter', 673.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (93, 'Timofei', 'Duplain', null, null, null, null, 'week', 5931.04);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (94, 'Kendrick', 'Bryden', null, false, true, false, 'week', 155.77);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (95, 'Muhammad', 'Elliot', 'Czech Republic', false, false, true, 'month', 632.99);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (96, 'Hilarius', 'Lordon', 'Czech Republic', false, false, false, 'quarter', 2681.85);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (97, 'Jabez', 'Loveless', null, false, true, false, 'year', 1062.96);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (98, 'Sloane', 'Novak', 'Poland', null, null, null, 'week', 5226.23);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (99, 'Mara', 'Riggulsford', null, true, true, false, 'month', 4491.12);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (100, 'Derry', 'Wesgate', 'Poland', true, true, false, 'year', 4096.07);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (101, 'Stanly', 'Clementson', 'Poland', true, true, false, 'week', 2254.74);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (102, 'Krista', 'Tokley', null, false, true, false, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (103, 'Luisa', 'Melesk', 'Czech Republic', false, true, true, 'week', 1183.18);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (104, 'Thorvald', 'Stroder', null, false, false, false, 'quarter', 755.41);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (105, 'Katerine', 'Barlie', null, true, false, true, 'week', 267.72);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (106, 'Janith', 'Patsall', null, true, true, true, 'month', 5125.17);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (107, 'Tully', 'Nettleship', 'Poland', null, null, null, 'week', 4680.83);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (108, 'Fred', 'Bernet', null, false, false, false, 'week', 3299.12);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (109, 'Harrie', 'Rikard', null, null, null, null, 'quarter', 10.99);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (110, 'Colline', 'Plane', 'Poland', true, false, false, 'week', 5388.82);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (111, 'Kay', 'Caygill', 'Poland', false, false, false, 'year', 3166.17);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (112, 'Gwendolyn', 'Charlin', 'Poland', false, false, true, 'month', 2547.29);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (113, 'Timoteo', 'Bevans', null, true, false, true, 'quarter', 2666.22);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (114, 'Kaia', 'Fullom', 'Poland', true, true, true, 'quarter', 5357.4);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (115, 'Edee', 'Leversha', null, false, true, true, 'month', 204.06);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (116, 'Constantino', 'Trodd', 'Germany', true, true, false, 'quarter', 5164.53);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (117, 'Mano', 'Strowlger', null, true, false, true, 'year', 451.85);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (118, 'Shurlocke', 'Dunston', null, true, false, false, 'month', 4421.96);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (119, 'Henryetta', 'Solloway', null, false, true, true, 'month', 3065.29);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (120, 'Dwain', 'Pluck', 'Poland', false, false, false, 'month', 625.03);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (121, 'Alexandra', 'Liversedge', 'Poland', true, false, false, 'year', 5784.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (122, 'Cornelle', 'Sprouls', 'Poland', false, true, true, 'month', 5401.51);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (123, 'Griz', 'Dwelling', 'Czech Republic', false, false, false, 'month', 5646.09);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (124, 'Pearce', 'Paggitt', null, true, false, true, 'month', 5982.58);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (125, 'Sharline', 'Sonier', 'Czech Republic', false, false, true, 'year', 19.11);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (126, 'Joly', 'Kepling', 'Poland', false, false, true, 'week', 4288.29);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (127, 'Melantha', 'St Ledger', null, true, true, false, 'week', 1854.48);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (128, 'Othella', 'Harner', 'Poland', null, null, null, 'week', 2302.01);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (129, 'Breanne', 'Ferroni', null, true, true, true, 'year', 3356.45);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (130, 'Lorena', 'Gladwell', null, true, true, false, 'year', 5581.12);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (131, 'Flory', 'Lyfe', null, null, null, null, 'week', 5695.58);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (132, 'Edythe', 'Oubridge', 'Poland', true, true, true, 'quarter', 4374.2);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (133, 'Zackariah', 'Treen', 'Czech Republic', true, true, false, 'quarter', 1651.72);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (134, 'Noella', 'Rapp', 'Poland', false, false, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (135, 'Armin', 'Rendell', 'Czech Republic', true, true, false, 'week', 1785.0);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (136, 'Tommy', 'Labusch', null, false, true, true, 'quarter', 3924.14);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (137, 'Niles', 'Gardner', 'Poland', true, false, true, 'week', 1456.51);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (138, 'Cortie', 'McQuilty', 'Czech Republic', false, false, true, 'month', 5497.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (139, 'Ivie', 'Biaggioli', 'Poland', false, false, true, 'week', 4125.17);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (140, 'Vaughn', 'Alabaster', null, false, true, true, 'year', 1454.74);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (141, 'Melanie', 'Sawyer', null, false, false, true, 'year', 4361.42);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (142, 'Gael', 'Paler', null, true, true, true, 'week', 1587.77);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (143, 'Xenia', 'Wroth', 'Germany', true, false, true, 'quarter', 700.22);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (144, 'Wallace', 'Wallis', 'Czech Republic', true, true, false, 'year', 4495.73);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (145, 'Gordy', 'Pratte', null, false, false, false, 'week', 3004.26);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (146, 'Fairleigh', 'Humberstone', null, false, true, true, 'week', 4026.74);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (147, 'Gunther', 'Battell', 'Czech Republic', true, true, false, 'month', 166.2);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (148, 'Pace', 'Churchyard', 'Poland', null, null, null, 'week', 1132.83);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (149, 'Timmy', 'Peploe', 'Poland', true, true, true, 'month', 743.32);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (150, 'Ramona', 'De Ruel', null, false, true, false, 'week', 3490.52);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (151, 'Trudi', 'Vauter', 'Poland', false, true, true, 'month', 4915.65);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (152, 'Ricky', 'Ludovico', 'Czech Republic', false, false, true, 'month', 4432.51);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (153, 'Arlina', 'Balsdone', 'Czech Republic', true, true, true, 'week', 2755.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (154, 'Timoteo', 'Scutter', null, false, false, false, 'quarter', 2563.59);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (155, 'Laverne', 'Penketh', 'Poland', false, false, false, 'week', 4191.44);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (156, 'Bobbie', 'Siemianowicz', 'Poland', false, false, true, 'week', 1384.35);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (157, 'Orlando', 'Lapides', null, true, false, false, 'quarter', 985.39);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (158, 'Bibby', 'Butterwick', 'Poland', false, true, true, 'week', 982.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (159, 'Torin', 'Hassett', null, false, false, true, 'week', 1914.68);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (160, 'Tony', 'Hugnot', 'Poland', true, true, false, 'quarter', 2406.6);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (161, 'Paddy', 'Battaille', 'Poland', false, false, true, 'quarter', 1016.97);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (162, 'Barbabas', 'Pigdon', null, true, false, true, 'week', 3414.38);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (163, 'Rodge', 'Pace', 'Poland', true, false, true, 'quarter', 4703.85);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (164, 'Justina', 'Bethel', 'Poland', false, true, true, 'week', 3312.21);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (165, 'Reina', 'Pulley', 'Poland', false, true, false, 'month', 2867.81);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (166, 'Janel', 'Ganning', null, false, true, true, 'quarter', 3938.33);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (167, 'Abigale', 'Dows', 'Czech Republic', false, false, false, 'year', 3855.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (168, 'Carmella', 'Rutt', null, false, true, false, 'quarter', 3768.74);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (169, 'Karoly', 'Dismore', null, true, false, false, 'week', 3591.24);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (170, 'Ranee', 'Simone', 'Czech Republic', false, true, true, 'week', 638.57);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (171, 'Winna', 'Butrimovich', null, false, false, false, 'month', 1034.19);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (172, 'Lothaire', 'Forshaw', 'Poland', false, false, false, 'week', 2564.71);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (173, 'Matthew', 'Bricham', 'Czech Republic', false, false, false, 'month', 5008.6);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (174, 'Colin', 'Tyhurst', 'Czech Republic', false, false, false, 'year', 1946.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (175, 'Stafani', 'Kares', null, false, true, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (176, 'Michale', 'Nowland', 'Poland', true, false, false, 'month', 3135.73);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (177, 'Aloysia', 'Luparto', null, false, false, false, 'year', 1721.74);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (178, 'Sheelagh', 'Alfonsetto', 'Czech Republic', false, true, false, 'month', 1242.79);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (179, 'Jehanna', 'Mochar', null, null, null, null, 'week', 5039.44);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (180, 'Debby', 'Cridland', null, true, false, true, 'week', 1202.48);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (181, 'Svend', 'Wastell', null, true, true, true, 'quarter', 904.7);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (182, 'Rockie', 'Simonnin', 'Czech Republic', true, false, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (183, 'Madonna', 'Olenikov', null, true, false, false, 'quarter', 3297.58);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (184, 'Genovera', 'Zink', 'Poland', true, false, false, 'year', 1846.99);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (185, 'Sharron', 'Thayre', 'Poland', false, false, false, 'quarter', 597.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (186, 'Courtnay', 'Matuschek', 'Poland', false, true, true, 'year', 89.66);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (187, 'Bari', 'Shelton', null, true, true, false, 'quarter', 3614.97);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (188, 'Bronson', 'Alleyne', 'Czech Republic', true, false, false, 'week', 623.2);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (189, 'Odie', 'Marlin', null, true, true, true, 'week', 2761.97);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (190, 'Moss', 'Pulbrook', 'Poland', null, null, null, 'quarter', 3581.5);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (191, 'Fernanda', 'Pimley', 'Czech Republic', null, null, null, 'quarter', 4603.52);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (192, 'Sylvan', 'Moreton', null, false, false, false, 'quarter', 3538.34);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (193, 'Allard', 'Pickton', 'Poland', false, true, false, 'year', 3736.5);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (194, 'Ernaline', 'Brigman', 'Poland', false, false, false, 'year', 3114.09);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (195, 'Stormy', 'Dibb', 'Czech Republic', true, false, true, 'year', 3261.8);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (196, 'Georgie', 'Gergely', null, true, false, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (197, 'Hedvig', 'Cornillot', 'Austria', false, true, true, 'quarter', 3293.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (198, 'Maribelle', 'Fairlaw', 'Germany', null, null, null, 'quarter', 1052.26);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (199, 'Nola', 'Seatter', 'Poland', true, true, false, 'year', 3796.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (200, 'Antonina', 'Alton', 'Poland', null, null, null, 'quarter', 1960.49);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (201, 'Lorrie', 'Ortet', 'Czech Republic', false, false, false, 'quarter', 867.14);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (202, 'Jarad', 'Blurton', 'Czech Republic', true, false, true, 'week', 1378.71);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (203, 'Ilsa', 'Stebbin', 'Czech Republic', true, false, true, 'week', 5235.39);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (204, 'Norine', 'Coopland', 'Czech Republic', true, true, false, 'quarter', 4372.45);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (205, 'Timothea', 'Canby', null, false, true, false, 'quarter', 5652.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (206, 'Adolpho', 'Dener', null, false, false, true, 'week', 5157.83);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (207, 'Hart', 'Trayes', null, true, false, true, 'month', 2167.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (208, 'Di', 'Paffitt', 'Czech Republic', false, true, false, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (209, 'Tally', 'Heritege', 'Poland', false, true, false, 'week', 4162.71);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (210, 'Robinson', 'Thrasher', null, false, false, true, 'month', 4343.35);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (211, 'Julee', 'Pheazey', null, true, true, true, 'month', 2163.84);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (212, 'Gerri', 'Tunn', 'Czech Republic', true, true, false, 'year', 5523.21);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (213, 'Edwina', 'Sloy', 'Poland', true, false, false, 'year', 1619.0);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (214, 'Josey', 'Commusso', null, false, true, false, 'quarter', 1833.99);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (215, 'Reinwald', 'Iglesias', null, false, false, false, 'year', 2679.14);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (216, 'Neils', 'Basso', 'Poland', false, false, false, 'quarter', 3099.59);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (217, 'Prue', 'Gandley', 'Poland', true, true, false, 'week', 390.24);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (218, 'Leonanie', 'Collin', 'Poland', true, false, true, 'month', 3197.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (219, 'Kellen', 'Waggitt', 'Poland', true, false, false, 'month', 2899.8);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (220, 'Kayley', 'Balentyne', null, true, false, true, 'quarter', 1033.94);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (221, 'Grethel', 'Blundel', 'Poland', false, false, true, 'quarter', 1443.2);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (222, 'Cyril', 'Draper', 'Czech Republic', false, true, true, 'year', 5249.66);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (223, 'Dolores', 'Roggerone', 'Poland', false, false, true, 'week', 1596.72);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (224, 'Jermaine', 'Farrear', 'Poland', false, true, false, 'month', 2020.58);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (225, 'Karolina', 'Minards', 'Poland', false, true, true, 'month', 2888.26);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (226, 'Paige', 'Splain', null, false, false, true, 'month', 1904.42);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (227, 'Lezlie', 'Silber', 'Poland', true, false, true, 'quarter', 4637.47);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (228, 'Lanny', 'O''Shea', 'Poland', true, true, false, 'quarter', 2454.4);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (229, 'Rosalie', 'Godrich', null, true, true, true, 'quarter', 3465.88);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (230, 'Adrienne', 'Oakeby', null, false, true, true, 'month', 2175.11);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (231, 'Silvana', 'Robertz', 'Czech Republic', false, true, false, 'week', 4898.62);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (232, 'Hedwig', 'Stockall', 'Poland', true, true, true, 'month', 4144.35);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (233, 'Verla', 'Ganforthe', 'Poland', false, true, false, 'month', 1064.01);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (234, 'Coraline', 'Tripcony', 'Czech Republic', false, false, false, 'quarter', 1219.61);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (235, 'Jacki', 'Crookshank', 'Poland', false, false, true, 'week', 841.76);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (236, 'Deena', 'Bradbeer', 'Czech Republic', false, false, true, 'year', 999.07);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (237, 'Sarita', 'Santostefano.', null, false, true, true, 'month', 4339.35);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (238, 'Frederick', 'Kirrage', 'Poland', false, true, true, 'quarter', 2583.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (239, 'Stefanie', 'Wardingly', 'Poland', false, false, true, 'year', 2770.25);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (240, 'Florinda', 'Borles', null, true, true, true, 'week', 13.63);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (241, 'Shem', 'Stepto', null, false, false, true, 'week', 4533.31);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (242, 'Valeria', 'Pearlman', 'Czech Republic', null, null, null, 'year', 4308.85);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (243, 'Delcina', 'Buick', 'Poland', true, true, false, 'quarter', 1230.51);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (244, 'Row', 'Wybourne', 'Czech Republic', true, true, false, 'week', 3173.33);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (245, 'Linzy', 'Dines', 'Czech Republic', true, true, false, 'week', 4158.53);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (246, 'Zara', 'Burlay', null, null, null, null, 'quarter', 5784.14);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (247, 'Diane-marie', 'Van Merwe', 'Poland', false, true, false, 'month', 559.46);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (248, 'Salvador', 'Flay', 'Czech Republic', false, true, true, 'month', 4820.75);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (249, 'Eva', 'Drysdall', 'Poland', null, null, null, 'week', 1332.62);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (250, 'Ethelbert', 'Espinet', 'Poland', true, false, true, 'month', 3677.45);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (251, 'Giffer', 'Slane', null, true, false, false, 'month', 672.85);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (252, 'Mirella', 'Posnett', null, true, true, false, 'quarter', 395.13);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (253, 'Manda', 'Volkes', 'Germany', true, true, true, 'quarter', 78.12);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (254, 'Obadiah', 'Allenson', 'Czech Republic', true, false, false, 'year', 1274.26);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (255, 'Sandor', 'Leghorn', 'Poland', true, false, false, 'week', 1349.33);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (256, 'Lindsey', 'Le Brum', null, false, false, false, 'week', 182.88);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (257, 'Lane', 'Plowright', 'Czech Republic', true, true, true, 'month', 5760.73);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (258, 'Darsie', 'Tesimon', 'Poland', false, false, true, 'year', 1105.33);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (259, 'Taylor', 'Nugent', 'Poland', true, true, false, 'year', 3462.72);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (260, 'Price', 'Rennox', 'Poland', true, true, true, 'week', 5762.09);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (261, 'Joelie', 'Rosita', 'Poland', false, false, true, 'quarter', 5230.79);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (262, 'Cherie', 'Scougal', 'Poland', true, false, false, 'year', 5122.56);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (263, 'Gardener', 'Creenan', 'Poland', false, true, false, 'quarter', 5280.36);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (264, 'Elisabeth', 'Linebarger', 'Czech Republic', null, null, null, 'year', 1986.12);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (265, 'Andee', 'Haith', 'Czech Republic', true, false, false, 'week', 5528.2);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (266, 'Sherlocke', 'Cargenven', null, true, true, false, 'week', 4519.4);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (267, 'Danna', 'Zavattero', null, false, false, true, 'quarter', 1552.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (268, 'Jesus', 'Skyrme', 'Czech Republic', false, true, false, 'quarter', 821.07);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (269, 'Constancia', 'Jarrett', 'Poland', true, false, false, 'week', 4812.29);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (270, 'Evangelina', 'Antognelli', 'Poland', false, false, true, 'year', 2780.8);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (271, 'Marys', 'Craythorn', 'Poland', true, false, false, 'week', 5645.36);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (272, 'Edward', 'Ketts', null, true, true, false, 'quarter', 5579.14);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (273, 'Fleming', 'Sheldrake', null, false, true, true, 'week', 5445.18);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (274, 'Coretta', 'Euesden', 'Poland', false, true, false, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (275, 'Kimbell', 'Turner', 'Poland', false, true, true, 'week', 1531.17);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (276, 'Sheba', 'Ashpole', 'Poland', null, null, null, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (277, 'Tanhya', 'Brightwell', 'Poland', false, false, false, 'week', 219.4);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (278, 'Johnette', 'Halsall', 'Poland', null, null, null, 'week', 1303.67);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (279, 'Petronille', 'Lilbourne', 'Poland', false, false, true, 'month', 5927.22);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (280, 'Arron', 'Aleksandrov', 'Czech Republic', true, false, false, 'month', 1719.0);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (281, 'Kyrstin', 'Catling', 'Czech Republic', null, null, null, 'week', 5242.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (282, 'Lilia', 'Hallagan', null, false, false, true, 'year', 207.13);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (283, 'Lorelei', 'Fulop', 'Poland', true, false, false, 'week', 590.37);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (284, 'Lutero', 'Tiesman', null, null, null, null, 'quarter', 5773.9);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (285, 'Devin', 'Cardon', 'Czech Republic', false, true, false, 'quarter', 5349.99);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (286, 'Ellen', 'Fumagallo', null, true, false, false, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (287, 'Bobbette', 'Weildish', 'Czech Republic', false, false, false, 'year', 4313.83);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (288, 'Allina', 'Laugheran', 'Czech Republic', false, true, false, 'quarter', 5270.12);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (289, 'Marlie', 'Hunnicutt', 'Poland', false, false, false, 'year', 274.54);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (290, 'Fidole', 'Conor', null, false, true, true, 'quarter', 1741.86);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (291, 'Annaliese', 'Ungerer', 'Poland', false, false, false, 'month', 2324.19);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (292, 'Malachi', 'Cowans', 'Czech Republic', true, false, false, 'month', 5601.12);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (293, 'Lusa', 'Danskine', 'Czech Republic', false, false, false, 'week', 5868.36);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (294, 'Jean', 'April', null, false, false, false, 'month', 1668.04);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (295, 'Laney', 'Minnock', null, false, false, false, 'quarter', 5973.73);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (296, 'Fredek', 'Vasilik', 'Czech Republic', true, false, true, 'month', 2285.47);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (297, 'Keven', 'Mingo', 'Germany', false, false, false, 'week', 2133.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (298, 'Quillan', 'Larkworthy', 'Poland', false, false, true, 'year', 1855.28);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (299, 'Anthiathia', 'Brockest', null, false, true, true, 'quarter', 3760.67);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (300, 'Hildegarde', 'Ciccone', 'Poland', true, false, false, 'month', 4703.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (301, 'Rebekah', 'Flanaghan', null, true, false, true, 'quarter', 113.7);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (302, 'Debbi', 'Dominighi', 'Czech Republic', false, false, false, 'week', 2563.92);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (303, 'Gerhardine', 'Brankley', 'Poland', true, false, false, 'month', 5155.61);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (304, 'Keri', 'Baigent', 'Poland', true, false, true, 'quarter', 2855.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (305, 'Yance', 'Brockherst', null, false, true, true, 'quarter', 2280.17);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (306, 'Fanchette', 'Sutheran', null, false, true, false, 'month', 1504.37);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (307, 'Coralyn', 'Joules', 'Poland', false, false, false, 'month', 107.6);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (308, 'Joelle', 'Laister', 'Czech Republic', true, true, false, 'quarter', 401.9);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (309, 'Minnnie', 'Winterbotham', null, true, true, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (310, 'Sumner', 'Parks', 'Poland', true, true, false, 'week', 473.5);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (311, 'Kipp', 'Cantrill', 'Germany', true, false, false, 'year', 4575.33);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (312, 'Dalenna', 'Elnor', null, null, null, null, 'month', 3702.21);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (313, 'Keely', 'Catling', 'Poland', true, false, false, 'quarter', 2966.15);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (314, 'Peirce', 'Raynard', 'Czech Republic', null, null, null, 'week', 1746.63);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (315, 'Philipa', 'Bysshe', 'Czech Republic', false, true, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (316, 'Kerianne', 'Naden', 'Czech Republic', true, false, true, 'week', 954.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (317, 'Neal', 'Lewknor', null, false, false, true, 'quarter', 1016.7);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (318, 'Gil', 'Suggitt', 'Czech Republic', false, false, true, 'quarter', 1287.96);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (319, 'Wynne', 'Faux', null, true, false, true, 'quarter', 374.67);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (320, 'Myrlene', 'Coghlin', 'Czech Republic', null, null, null, 'week', 3159.47);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (321, 'Lonee', 'Paz', 'Poland', false, true, false, 'month', 4947.11);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (322, 'Boycey', 'Letrange', 'Poland', true, false, false, 'year', 1976.29);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (323, 'Ingrim', 'Matuszkiewicz', null, true, false, true, 'quarter', 525.93);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (324, 'Scarlett', 'Rathbone', 'Poland', false, false, true, 'year', 4523.55);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (325, 'Sibyl', 'Gaskoin', 'Czech Republic', false, false, false, 'week', 1716.57);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (326, 'Nicolas', 'Launder', 'Poland', true, true, true, 'week', 2981.03);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (327, 'Eddy', 'Dupey', 'Poland', true, true, true, 'quarter', 3608.54);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (328, 'Roarke', 'Nicholl', 'Poland', false, false, true, 'quarter', 2783.82);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (329, 'Renaud', 'Oakenfull', 'Poland', false, false, true, 'year', 5358.04);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (330, 'Noah', 'Rickis', null, true, true, true, 'year', 3358.39);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (331, 'Felita', 'Layborn', 'Czech Republic', false, false, false, 'year', 2480.22);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (332, 'Gayleen', 'Mathey', null, true, false, false, 'year', 4412.64);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (333, 'Aguie', 'Pingstone', 'Poland', true, false, true, 'month', 86.81);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (334, 'Aylmar', 'Guiraud', 'Poland', true, true, true, 'year', 1207.08);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (335, 'Henrik', 'Thorald', 'Poland', true, false, false, 'week', 3873.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (336, 'Craggie', 'Lovelock', null, true, true, true, 'quarter', 1530.88);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (337, 'Millard', 'Feltoe', 'Czech Republic', null, null, null, 'quarter', 743.17);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (338, 'Poppy', 'Kennally', null, true, false, false, 'week', 3544.34);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (339, 'Benjie', 'Bishell', 'Poland', true, true, false, 'week', 882.42);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (340, 'Amble', 'Masserel', null, true, false, false, 'month', 3564.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (341, 'Meredith', 'Genn', 'Poland', null, null, null, 'year', 1980.16);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (342, 'Antonin', 'Trematick', null, false, true, true, 'month', 4429.86);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (343, 'Marina', 'Heephy', null, true, true, false, 'year', 3121.74);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (344, 'Justis', 'Cockshot', 'Poland', true, true, true, 'year', 2098.42);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (345, 'Madge', 'Hanscomb', 'Czech Republic', false, false, true, 'month', 228.08);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (346, 'Lief', 'Coxon', 'Czech Republic', false, false, false, 'year', 1881.53);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (347, 'Mordy', 'Form', 'Poland', true, false, true, 'month', 1767.81);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (348, 'Barbee', 'Aronstein', 'Poland', true, false, false, 'month', 1935.91);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (349, 'Cthrine', 'Minchell', 'Czech Republic', true, true, true, 'year', 5550.52);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (350, 'Dona', 'Rosengren', 'Poland', false, true, true, 'year', 2859.26);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (351, 'Letty', 'Chessor', null, false, false, true, 'year', 292.62);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (352, 'Erroll', 'Kensit', null, true, true, true, 'year', 2314.67);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (353, 'Deloris', 'Penddreth', null, true, false, false, 'week', 3688.5);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (354, 'Danica', 'Bodham', 'Poland', true, true, false, 'quarter', 5069.23);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (355, 'Meryl', 'Ladewig', 'Czech Republic', true, false, true, 'month', 5988.54);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (356, 'Lynnea', 'Swinden', 'Czech Republic', true, false, false, 'year', 4338.64);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (357, 'Robinette', 'Brittian', 'Poland', true, true, false, 'year', 3324.39);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (358, 'Valery', 'Cocksedge', 'Poland', false, true, true, 'week', 3573.92);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (359, 'Petra', 'Booeln', 'Czech Republic', false, false, false, 'month', 2111.28);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (360, 'Shelba', 'Somerset', null, true, true, false, 'month', 3164.23);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (361, 'Sharron', 'Anespie', null, true, false, false, 'year', 5216.79);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (362, 'Major', 'McIntee', null, false, false, true, 'week', 1318.01);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (363, 'Carlyn', 'Marnes', 'Poland', false, true, false, 'month', 5685.63);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (364, 'Georgianna', 'Romans', null, true, false, true, 'week', 1726.22);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (365, 'Laina', 'Blenkiron', 'Poland', false, false, false, 'year', 1874.52);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (366, 'Kamila', 'Eastman', 'Poland', false, true, false, 'week', 1059.31);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (367, 'Ignatius', 'Fucher', null, false, true, false, 'year', 3274.21);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (368, 'Nanete', 'Nuzzti', 'Poland', false, false, true, 'quarter', 1220.2);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (369, 'Dayle', 'Braddon', 'Poland', false, true, false, 'year', 2881.0);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (370, 'Stephannie', 'Devennie', null, false, false, true, 'quarter', 4769.99);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (371, 'Spence', 'Hocking', 'Poland', false, true, false, 'week', 5538.66);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (372, 'Jase', 'Zoppie', null, null, null, null, 'quarter', 5779.67);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (373, 'Peta', 'Couzens', null, true, true, false, 'year', 1458.73);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (374, 'Ketti', 'Smees', 'Germany', null, null, null, 'quarter', 137.04);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (375, 'Kacey', 'Dudgeon', 'Czech Republic', false, true, true, 'year', 2667.75);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (376, 'Elwira', 'Hrinchishin', 'Poland', null, null, null, 'week', 1436.84);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (377, 'Romola', 'Decker', 'Poland', null, null, null, 'quarter', 730.3);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (378, 'Roland', 'Laughtisse', null, true, true, true, 'year', 3756.6);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (379, 'Lilyan', 'Strachan', 'Poland', true, true, true, 'quarter', 2710.23);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (380, 'Veradis', 'Nethercott', 'Poland', true, false, true, 'quarter', 2088.18);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (381, 'Ermina', 'Iori', 'Czech Republic', false, false, true, 'year', 2699.94);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (382, 'Florri', 'de Savery', 'Poland', true, true, true, 'week', 4749.04);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (383, 'Jessi', 'Morcom', 'Poland', true, true, true, 'month', 2870.44);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (384, 'Britni', 'Speeks', 'Poland', false, false, true, 'month', 1555.76);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (385, 'Rubia', 'Luttgert', 'Poland', true, false, false, 'year', 776.57);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (386, 'Julio', 'Naylor', 'Poland', false, true, false, 'year', 368.34);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (387, 'Pietrek', 'Lawly', null, null, null, null, 'quarter', 3938.31);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (388, 'Shelby', 'Standeven', null, true, false, false, 'quarter', 3349.73);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (389, 'Percival', 'Dourin', 'Czech Republic', true, true, false, 'week', 3185.51);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (390, 'Elvin', 'Piscopello', 'Poland', null, null, null, 'week', 1246.56);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (391, 'Erny', 'Trippett', 'Germany', true, false, false, 'week', 3405.14);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (392, 'Iggy', 'Sacco', 'Poland', true, false, false, 'year', 523.88);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (393, 'Lek', 'Harston', 'Poland', null, null, null, 'year', 5174.27);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (394, 'Hoyt', 'Budge', null, true, true, true, 'week', 5848.44);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (395, 'Lionel', 'Altimas', 'Poland', true, false, true, 'quarter', 1300.03);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (396, 'Lari', 'Humpage', null, false, true, false, 'year', 843.46);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (397, 'Jacquelyn', 'Canete', 'Poland', true, false, true, 'month', 3287.28);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (398, 'Bernadene', 'Creigan', 'Germany', true, false, false, 'month', 2622.77);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (399, 'Micky', 'Mellonby', 'Germany', false, false, false, 'week', 5489.46);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (400, 'Karin', 'Strange', 'Czech Republic', true, false, true, 'quarter', 990.22);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (401, 'Farly', 'Kennham', 'Poland', false, false, false, 'quarter', 2771.67);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (402, 'Padgett', 'MacKaile', 'Poland', null, null, null, 'quarter', 5565.87);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (403, 'Anita', 'Douche', null, false, true, true, 'month', 821.82);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (404, 'Diana', 'Alven', 'Poland', false, true, true, 'month', 2689.91);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (405, 'Reena', 'Simkiss', 'Czech Republic', false, false, true, 'year', 2779.13);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (406, 'Blanche', 'Cherryman', 'Germany', false, false, false, 'year', 2305.54);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (407, 'Dante', 'Giveen', null, false, true, false, 'year', 2270.83);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (408, 'Bernetta', 'Dober', 'Poland', true, false, false, 'quarter', 3497.31);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (409, 'Selia', 'Jenicke', 'Poland', false, false, false, 'month', 3207.9);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (410, 'Josee', 'McKyrrelly', 'Poland', true, true, true, 'month', 3932.87);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (411, 'Lara', 'Camlin', 'Poland', true, false, true, 'year', 3399.33);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (412, 'Alfreda', 'Brigstock', 'Czech Republic', true, false, true, 'month', 3083.07);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (413, 'Saunderson', 'Bedboro', null, false, false, false, 'month', 112.69);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (414, 'Shem', 'Tudbald', 'Poland', true, false, false, 'quarter', 4721.47);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (415, 'Tara', 'Edward', 'Czech Republic', false, true, false, 'week', 3604.6);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (416, 'Bathsheba', 'Ropert', 'Czech Republic', true, false, false, 'week', 3983.76);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (417, 'Jannel', 'Wellington', null, false, false, true, 'year', 3504.7);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (418, 'Maure', 'Sherrard', 'Poland', true, false, true, 'quarter', 1595.56);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (419, 'Alyce', 'McMyler', null, false, true, false, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (420, 'Allsun', 'Frostdick', 'Czech Republic', false, false, true, 'quarter', 1203.95);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (421, 'Tansy', 'Leggis', 'Poland', true, false, true, 'month', 3408.57);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (422, 'Garner', 'Kurt', 'Poland', null, null, null, 'week', 4712.51);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (423, 'Tabbie', 'McDowall', 'Czech Republic', null, null, null, 'year', 5661.52);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (424, 'Mata', 'Triebner', 'Poland', true, true, false, 'year', 3496.49);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (425, 'Brigg', 'McKelvie', null, true, true, true, 'year', 1135.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (426, 'Elwood', 'Packer', 'Poland', false, false, false, 'week', 1465.08);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (427, 'Malissa', 'Southway', 'Poland', null, null, null, 'month', 845.08);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (428, 'Godiva', 'Alonso', 'Poland', false, false, false, 'quarter', 5087.77);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (429, 'Vassili', 'Heggs', 'Poland', false, true, false, 'year', 392.7);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (430, 'Catlin', 'Swansbury', 'Poland', false, false, false, 'quarter', 5283.07);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (431, 'Ilka', 'Woodworth', 'Poland', null, null, null, 'week', 3878.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (432, 'Gibb', 'Wink', null, false, true, false, 'month', 2563.88);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (433, 'Fraze', 'Lansdown', null, false, true, false, 'quarter', 5891.95);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (434, 'Deb', 'Mottini', null, false, false, true, 'quarter', 563.31);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (435, 'Lanny', 'Santi', 'Czech Republic', true, true, false, 'month', 5076.09);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (436, 'Evangelin', 'Debow', 'Poland', true, false, false, 'year', 1950.03);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (437, 'Kirsten', 'Walton', null, true, false, true, 'year', 5680.26);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (438, 'Nickola', 'Dinjes', 'Poland', true, false, false, 'quarter', 2063.16);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (439, 'Lissa', 'Guttridge', 'Germany', false, false, true, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (440, 'Kerrill', 'Gabbitas', null, false, false, false, 'year', 235.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (441, 'Delphine', 'Pursehouse', null, false, false, false, 'month', 1529.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (442, 'Pippo', 'Sutlieff', null, true, false, false, 'month', 169.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (443, 'Wildon', 'Meiner', null, true, false, false, 'quarter', 3330.23);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (444, 'Nikkie', 'Stephenson', 'Poland', false, false, false, 'year', 2058.96);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (445, 'Jenine', 'Willavoys', 'Poland', true, false, true, 'quarter', 5794.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (446, 'Halli', 'McKeon', 'Czech Republic', false, false, false, 'month', 3126.26);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (447, 'Freeman', 'Banaszczyk', 'Czech Republic', true, true, true, 'quarter', 375.35);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (448, 'Jeffie', 'Thoumas', null, false, false, true, 'year', 305.96);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (449, 'Reynold', 'Lynthal', null, true, true, true, 'quarter', 3374.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (450, 'Florina', 'Delgardo', 'Czech Republic', true, true, true, 'quarter', 1256.37);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (451, 'Clarinda', 'Duddan', 'Austria', true, true, true, 'month', 5111.98);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (452, 'Arron', 'Shepton', null, true, true, true, 'year', 2647.28);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (453, 'Morey', 'Fero', 'Poland', null, null, null, 'quarter', 1542.29);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (454, 'Genevieve', 'Vasilic', 'Czech Republic', false, false, false, null, null);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (455, 'Casar', 'McIlvaney', null, true, true, true, 'quarter', 3919.05);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (456, 'Howey', 'Walsham', null, false, false, true, 'quarter', 3629.46);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (457, 'Shelagh', 'Cocks', 'Germany', false, true, false, 'year', 792.42);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (458, 'Brennen', 'Honisch', 'Poland', false, true, false, 'year', 1744.06);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (459, 'Coralyn', 'Niess', 'Poland', null, null, null, 'year', 4367.03);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (460, 'Othella', 'Pascho', null, true, false, false, 'quarter', 2221.74);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (461, 'Saxon', 'Chattelaine', 'Poland', true, false, false, 'week', 5920.96);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (462, 'Darcy', 'Murrish', 'Poland', true, true, true, 'month', 4757.15);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (463, 'Babette', 'Darlington', 'Czech Republic', true, false, false, 'week', 2116.94);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (464, 'Hailey', 'Pretsell', 'Poland', false, true, true, 'quarter', 3768.03);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (465, 'Lorens', 'Lovelady', 'Czech Republic', null, null, null, 'week', 159.81);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (466, 'Nannette', 'Smickle', null, false, false, true, 'month', 3885.48);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (467, 'Tudor', 'Benkin', null, true, false, true, 'week', 3804.48);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (468, 'Shoshanna', 'Skirving', null, true, true, true, 'year', 572.7);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (469, 'Meir', 'Lewton', null, true, false, false, 'year', 721.55);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (470, 'Felicle', 'Henze', 'Poland', false, true, false, 'quarter', 1528.34);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (471, 'Dedie', 'Redrup', null, true, true, true, 'week', 1378.44);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (472, 'Ulick', 'Marquez', 'Poland', false, false, false, 'month', 3492.13);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (473, 'Brendan', 'Arthey', null, false, false, false, 'quarter', 5597.4);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (474, 'Kizzie', 'Tyer', null, null, null, null, 'quarter', 2850.37);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (475, 'Port', 'Pill', null, false, false, false, 'week', 3012.44);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (476, 'Lisette', 'Witty', 'Czech Republic', null, null, null, 'year', 2970.37);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (477, 'Isabella', 'Kiehne', 'Czech Republic', true, true, true, 'quarter', 1340.23);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (478, 'Maribeth', 'Cutmere', 'Poland', false, true, false, 'year', 4648.36);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (479, 'Carleton', 'Gagg', 'Poland', true, true, false, 'quarter', 868.43);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (480, 'Elfie', 'Robez', null, true, false, true, 'year', 674.73);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (481, 'Torey', 'Arling', null, true, true, false, 'month', 1927.69);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (482, 'Tamar', 'Jump', 'Poland', null, null, null, 'month', 4303.76);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (483, 'Hurley', 'Salack', 'Poland', false, false, false, 'month', 198.56);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (484, 'Latia', 'Elletson', 'Poland', true, false, true, 'quarter', 328.61);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (485, 'Allis', 'Burdikin', null, true, true, false, 'quarter', 4816.83);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (486, 'Birk', 'Dollimore', 'Czech Republic', false, false, false, 'week', 3739.64);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (487, 'Tull', 'Saldler', null, false, true, true, 'quarter', 5485.57);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (488, 'Dita', 'Mickleborough', null, null, null, null, 'quarter', 3044.71);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (489, 'Gwenneth', 'Harrowing', null, false, false, true, 'month', 3668.22);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (490, 'Maurise', 'Flaune', null, null, null, null, 'year', 3158.27);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (491, 'Benedikta', 'Gerretsen', null, true, false, true, 'week', 1185.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (492, 'Annnora', 'Starton', null, true, true, true, 'month', 3400.28);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (493, 'Ladonna', 'McMenamy', null, false, false, true, 'month', 4722.58);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (494, 'Lethia', 'Held', 'Czech Republic', false, false, false, 'year', 754.38);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (495, 'Loren', 'Macquire', null, true, false, false, 'week', 787.89);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (496, 'Dael', 'Maylam', 'Poland', false, false, true, 'year', 1799.72);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (497, 'Nonnah', 'Habens', null, false, true, false, 'year', 2629.06);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (498, 'Derward', 'Sandeford', 'Poland', null, null, null, 'year', 3559.92);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (499, 'Claudianus', 'Abelevitz', 'Germany', null, null, null, 'month', 145.19);
insert into client_zoo (id, first_name, last_name, location, cat, dog, other, frequency, sum_order) values (500, 'Colan', 'Goodey', 'Poland', true, false, false, 'month', 3293.49);
